---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mf-soundcheck-testing
  description: |
    Placeholder description...
  tags:
    - java
    - dsp
    - terra
    - springboot
    - broad-devops
  annotations:
    github.com/project-slug: databiosphere/mf-soundcheck-testing
spec:
  type: service
  lifecycle: experimental
  owner: broad-devops
  system: terra
  providesApis:
    - mf-soundcheck-testing-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mf-soundcheck-testing-api
  description: |
    Placeholder API description...
  tags:
    - java
    - dsp
    - terra
    - springboot
    - broad-devops
  annotations:
    github.com/project-slug: databiosphere/mf-soundcheck-testing
spec:
  type: openapi
  lifecycle: experimental
  system: terra
  owner: broad-devops
  definition:
    $text: ./service/src/main/resources/api/openapi.yml
---
